print("NAVEEN KUMAR")
print("Python")
#print("Core\advanced")
print("core\tadvanced")
#print("sathya "technology"")
#print("sathya"technology"")
print("================")
print("hi")
print("students,This is naveen,")
print("from satya tech,AMPT")
print("====================")
print("satya technologies")
print("naveen kumar\npython")
print("satya@'naveen'")
print("s@tya\"tech\"")
print("hello students this is 'naveen',")
#print("i am a \"python\"faculty in\"satya\")
print("i am a\"python\" faculty in \"satya\"")
print("my contact no is :'90100182749' ")
print("=================")
print(5+2)
print("satya"+"tech")
print("12-6")
print(10/2)
print("core","-","python")
print("corep-ython")
print("core","-","python")
print(5+2)
print("12"+"5")
print("satya","tech")
print("\n","satya","-","tech")
#print("python"+3)
print("python","+","3")
print(3+3,"+","python")
print("7-2")
print("satya","-","tech")
print("satya-tech")
print("satya\n\ttech")
print("satya\n\t'tech'")
print("**satya tech**")
print("\n---python---")
print("\t\tnaveen\tkumar")
print("\t\t======")